### PR TITLE
fr translation

### PR DESCRIPTION
**Pull request by sebnukem**
added doc/fr/ with all files translated into French.

Caution: also updated:
doc/language.json
garden.jade to fix a "`!!!` is deprecated, you must now use `doctype`" error when building

thank you

### CODE REVIEW

**Comment by timruffles** [comment]
Thanks! Can you merge these into one commit please? `git rebase -i` etc will help.

**Comment by sebnukem** [comment]
I'm sorry but git makes me feel like a retard. Is a

git reset --soft HASH-BEFORE-MY-FIRST

command ok as well?

**Comment by timruffles** [comment]
sure!

**Comment by sebnukem** [comment]
ok. there's now a single commit.

**Comment by sebnukem** [comment]
ok. there's now a single commit.

**Comment by peterjwest** [comment]
Merging, thanks!

**Comment by sebnukem** [comment]
Thank you!

**Comment by sebnukem** [comment]
Hello. When will you guys release this to the public web site?

**Pull request merged**
