### PR TITLE
Fix desktop nav

### PR DESCRIPTION
**Pull request by ivanov-v**
I fixed this problem
image

### CODE REVIEW

**Comment by peterjwest** [comment]
What browser/resolution was this occurring in? I can't replicate it

**Comment by ivanov-v** [comment]
Chrome 57.0.2987.110 (64-bit), Macbook Pro 15 Retina (2880x1800)

**Comment by peterjwest** [comment]
I can't replicate this (on exactly the same setup). Is it possible you have custom settings or a browser extension that causes it? Can you check Firefox?

**Comment by peterjwest** [comment]
Possibly a better test: do you get the same bug in Chrome canary?

**Comment by ivanov-v** [comment]
Last Canary


Last FF
ff

Last Safari
s

**Comment by peterjwest** [comment]
Ok, you convinced me. Thanks!

**Pull request merged**
