### PR TITLE
Add an important example to Closures setTimeout

### PR DESCRIPTION
**Pull request by SamMorrowDrums**
The additional argument to setTimeout wasn't mentioned, and it's a really neat way to achieve this.

### CODE REVIEW

**Comment by peterjwest** [comment]
Neat! I wouldn't say that 'behaves as a closure' though. It would be better to say 'this passes these arguments through to the callback'

**Comment by SamMorrowDrums** [comment]
Sure, will change that now

**Comment by timruffles** [comment]
Would it be possible to specify the legacy envs that don't support the
additional args please?

**Comment by SamMorrowDrums** [comment]
MDN specify it as ["passing additional parameters to the function in the first syntax does not work in Internet Explorer 9 and below"](https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers.setTimeout).

If you are happy I will just amend it to IE < 9;

**Comment by timruffles** [comment]
wonderful!

**Pull request merged**
