### PR TITLE
translation into Belorussian

### PR DESCRIPTION
**Pull request by vaukalak**

### CODE REVIEW

**Comment by vaukalak** [comment]
added doc/by/ with all files translated into Belorussian.

Caution: also updated:
doc/language.json

**Comment by timruffles** [comment]
Thanks!

**Comment by anibyl** [comment]
+1

**Comment by itsimoshka** [comment]
+1

**Comment by Ju1jan** [comment]
+1

**Comment by vaukalak** [comment]
Is there any issue with merging this?

**Comment by timruffles** [comment]
Nope! Sorry for the slow reply.

**Comment by vaukalak** [comment]
thanks a lot :)

**Pull request merged**
